# Generated by Django 2.2.1 on 2019-05-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaNam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
